name: SemVer Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}} -- ${{inputs.modules}}"

# Trigger workflow manually
on:
  workflow_dispatch:
    inputs:
      modules:
       type: choice
       description: Module
       required: true
       options:
        - --SELECT--
        - data-properties
        - tinkar-starter-data-properties
        - tinkar-example-data-properties
      release_version:
        type: string
        description: "(Optional) Custom Release Version"
        required: false
      version_type:
        description: 'Development version type to increment'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  BRANCH_NAME: ${{ github.ref_name }}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}
  MODULE: ${{inputs.modules == 'data-properties' && '.' || inputs.modules}}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    defaults:
      run:
       working-directory: ${{env.MODULE}}
    steps:
      - name: Verify Module Selection
        if: inputs.modules == '-- SELECT --'
        run: |
          echo "ERROR: Please pick a correct module from the selection"
          exit 1
          
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

      - name: Shared Release Action
        uses: ikmdev/maven-semver-release-action@v2.3.0
        with:
          version_type: ${{ github.event.inputs.version_type }}
          github_token: ${{secrets.GITHUB_TOKEN}}
          release_version: ${{ github.event.inputs.release_version }}
          mvn_additional_args: -Dproject.name=${{inputs.modules}}
